/* The run registry: generated by the engine (engine/run.ts appends to
   panel/data/runs.json). Newest first. Real runs only: mock-hunter gate. */
import data from "../data/runs.json";

export const runs = data;
